run:
	python manage.py runserver

migrate:
	python manage.py makemigrations
	python manage.py migrate

superuser:
	python manage.py createsuperuser

shell:
	python manage.py shell

install:
	poetry install

black:
	black .

start-db:
	docker start job-portal_db
