# Generated by Django 6.1.1 on 2026-09-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cover_letter_file",
            field=models.FileField(blank=True, null=True, upload_to="cover_letters/"),
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter_type",
            field=models.CharField(
                blank=True,
                choices=[("CLF", "cover_letter_file"), ("CLT", "cover_letter_text")],
                default="CLT",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
