# Generated by Django 6.1.1 on 2026-09-19 11:48

from django.db import migrations


def copy_cover_letter(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    for application in Application.objects.all():
        if application.cover_letter:
            application.cover_letter_text = application.cover_letter
            application.cover_letter_type = "CLT"
            application.save()


def reverse_copy_cover_letter(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    for application in Application.objects.all():
        if application.cover_letter_text:
            application.cover_letter = application.cover_letter_text
            application.save()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_cover_letter_file_and_more"),
    ]

    operations = [migrations.RunPython(copy_cover_letter, reverse_copy_cover_letter)]
