# Generated by Django 6.1.1 on 2026-09-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_copy_cover_letter_to_cover_letter_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="cover_letter",
        ),
    ]
